name = "server"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.31"
wisp = "~> 0.6"
gleam_erlang = "~> 0.22"
mist = "~> 0.14"
gleam_json = "~> 0.6"
gleam_http = "~> 3.5"
mungo = "~> 0.20"
bison = "~> 0.28"
dotenv_gleam = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 0.10"
